# Generated by Django 5.2.1 on 2025-07-15 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_At', verbose_name='Updated At')),
                ('title_nn', models.CharField(db_column='Title', max_length=100, verbose_name='video title')),
                ('url', models.URLField(db_column='URL', verbose_name='video url')),
                ('description', models.TextField(blank=True, db_column='Description', verbose_name='video description')),
                ('created_by', models.ForeignKey(db_column='Created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(db_column='Updated_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
