# Generated by Django 5.2.1 on 2025-09-22 02:39

import django.db.models.deletion
import django.utils.timezone
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "first_name_nn",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name_nn",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "phone_number_nn",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "address_nn",
                    models.CharField(max_length=200, verbose_name="address"),
                ),
                (
                    "location_nn",
                    models.CharField(max_length=200, verbose_name="location"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user_type_nn",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("admin", "Admin"),
                            ("super_admin", "Super_Admin"),
                            ("accountant", "Accountant"),
                            ("telecaller", "Telecaller"),
                            ("salesman", "Salesman"),
                            ("supervisor", "Supervisor"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="user type",
                    ),
                ),
                (
                    "residential_or_commercial",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_nn",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "registered_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_nn",
                    models.CharField(
                        choices=[
                            ("design_feedback", "Design Feedback"),
                            ("payment_issues", "Payment Issues"),
                            ("video_upload_problem", "Video Upload Problem"),
                            ("general_inquiry", "General Inquiry"),
                        ],
                        db_column="category",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("subject_nn", models.CharField(max_length=400)),
                ("message_nn", models.TextField()),
                (
                    "screenshots",
                    models.ImageField(
                        blank=True,
                        db_column="screenshots",
                        null=True,
                        upload_to=users.utils.upload_screenshot_path,
                        verbose_name="Screenshots",
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="username",
                    ),
                ),
            ],
        ),
    ]
