# Generated by Django 5.2.1 on 2025-09-22 02:39

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="BrandType",
                        max_length=50,
                        unique=True,
                        verbose_name="BrandType",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        db_column="Client_Name",
                        help_text="Full name of the prospective customer",
                        max_length=100,
                        verbose_name="Client Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="Email_Address",
                        help_text="Contact email address",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_column="Phone_Number",
                        help_text="Contact phone number",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "call_back_time",
                    models.TimeField(
                        blank=True,
                        db_column="Call_Back_Time",
                        null=True,
                        verbose_name="Call-Back Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("Follow-up", "Follow-up"),
                            ("Contacted", "Contacted"),
                            ("Quoted", "Quoted"),
                            ("Converted", "Converted"),
                            ("Rejected", "Rejected"),
                        ],
                        db_column="Status",
                        default="New",
                        help_text="Current stage in the sales process",
                        max_length=20,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "society_name",
                    models.CharField(
                        blank=True,
                        db_column="Society_Name",
                        max_length=255,
                        null=True,
                        verbose_name="Society Name",
                    ),
                ),
                (
                    "flat_number",
                    models.CharField(
                        blank=True,
                        db_column="Flat_Number",
                        max_length=50,
                        null=True,
                        verbose_name="Flat Number",
                    ),
                ),
                (
                    "flat_type",
                    models.CharField(
                        blank=True,
                        db_column="Flat_Type",
                        max_length=50,
                        null=True,
                        verbose_name="Flat Type",
                    ),
                ),
                (
                    "bhk_room_type",
                    models.JSONField(
                        blank=True,
                        db_column="BHK_Room_Type",
                        default=list,
                        null=True,
                        verbose_name="BHK Room Type",
                    ),
                ),
                (
                    "possession_date",
                    models.DateField(
                        blank=True,
                        db_column="Possession_Date",
                        null=True,
                        verbose_name="Possession Date",
                    ),
                ),
                (
                    "service_type",
                    models.JSONField(
                        blank=True,
                        db_column="Service_Type",
                        default=list,
                        null=True,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "service_type_description",
                    models.TextField(
                        blank=True,
                        db_column="Service_Type_Description",
                        null=True,
                        verbose_name="Service Type Description",
                    ),
                ),
                (
                    "rooms_to_design",
                    models.JSONField(
                        blank=True,
                        db_column="Rooms_To_Design",
                        default=list,
                        null=True,
                        verbose_name="Rooms_To_Design",
                    ),
                ),
                (
                    "kitchen_platform_status",
                    models.BooleanField(
                        blank=True,
                        db_column="Kitchen_Platform_Status",
                        default=False,
                        null=True,
                        verbose_name="Kitchen Platform Status",
                    ),
                ),
                (
                    "kitchen_platform_description",
                    models.CharField(
                        blank=True,
                        db_column="Kitchen_Platform_Description",
                        max_length=300,
                        null=True,
                        verbose_name="Kitchen Platform Description",
                    ),
                ),
                (
                    "civil_work_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Granite Work", "Granite Work"),
                            ("Plumbing Work", "Plumbing Work"),
                            ("Electrical Work", "Electrical Work"),
                            ("Tiles Work", "Tiles Work"),
                            ("Other", "Other"),
                        ],
                        db_column="Civil_Work_Type",
                        max_length=20,
                        null=True,
                        verbose_name="Civil Work Type",
                    ),
                ),
                (
                    "preferred_brand_type",
                    models.JSONField(
                        blank=True,
                        db_column="Preferred_Material",
                        default=list,
                        null=True,
                        verbose_name="Preferred Material",
                    ),
                ),
                (
                    "floor_plan",
                    models.FileField(
                        blank=True,
                        db_column="Floor_Plan_Details",
                        max_length=255,
                        null=True,
                        upload_to=utils.utils.file_upload_path,
                        verbose_name="Floor Plan Details",
                    ),
                ),
                (
                    "budget_range",
                    models.DecimalField(
                        blank=True,
                        db_column="Budget_Range",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget Range (INR)",
                    ),
                ),
                (
                    "past_experience",
                    models.BooleanField(
                        blank=True,
                        db_column="Previous_Design_Experience",
                        default=False,
                        null=True,
                        verbose_name="Previous Interior Design Experience?",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        db_column="Experience_Details",
                        null=True,
                        verbose_name="Experience Details",
                    ),
                ),
                (
                    "follow_up_dt",
                    models.DateField(
                        blank=True,
                        db_column="Follow_up_Date",
                        help_text="Calendar date to follow up with the customer",
                        null=True,
                        verbose_name="Follow-up Date",
                    ),
                ),
                (
                    "is_reminder",
                    models.BooleanField(
                        db_column="Is_Reminder",
                        default=False,
                        help_text="Whether to send a reminder for this follow-up",
                        verbose_name="Enable Reminder",
                    ),
                ),
                (
                    "follow_up_note",
                    models.CharField(
                        blank=True,
                        db_column="Follow_Up_Note",
                        max_length=300,
                        null=True,
                        verbose_name="Follow-Up Note",
                    ),
                ),
                (
                    "follow_up_at",
                    models.TimeField(
                        blank=True,
                        db_column="Follow_up_at",
                        null=True,
                        verbose_name="Follow-up Time",
                    ),
                ),
                (
                    "mark_as_done",
                    models.BooleanField(
                        db_column="Mark_as_Done",
                        default=False,
                        verbose_name="Mark as Done",
                    ),
                ),
                (
                    "interest_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="Interest_Level_Percent",
                        null=True,
                        verbose_name="Interest Level (%)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Website", "Website"),
                            ("Referral", "Referral"),
                            ("Social Media", "Social Media"),
                            ("Advertisement", "Advertisement"),
                            ("Phone Call", "Phone Call"),
                            ("Other", "Other"),
                        ],
                        db_column="Lead_Source",
                        help_text="How did the customer find us",
                        max_length=20,
                        null=True,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "is_converted_to_client",
                    models.BooleanField(
                        db_column="Is_Converted_To_Client",
                        default=False,
                        verbose_name="Converted to Client",
                    ),
                ),
                (
                    "conversion_date",
                    models.DateTimeField(
                        blank=True,
                        db_column="Conversion_Date",
                        null=True,
                        verbose_name="Conversion Date",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_column="City",
                        default="Hyderabad",
                        help_text="Customer's city location",
                        max_length=100,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "move_in_date",
                    models.DateField(
                        blank=True,
                        db_column="Move_In_Date",
                        null=True,
                        verbose_name="Move In Date",
                    ),
                ),
                (
                    "move_in_date_details",
                    models.TextField(
                        blank=True,
                        db_column="Move In Date Details",
                        null=True,
                        verbose_name="Move_In_Date_Details",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Lead",
                "verbose_name_plural": "Customer Leads",
                "db_table": "customer_lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        db_column="File_Name",
                        max_length=100,
                        null=True,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file_size",
                    models.DecimalField(
                        blank=True,
                        db_column="File_Size",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="File Size (MB)",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leads/",
                        verbose_name="File Attachment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead File",
                "verbose_name_plural": "Lead Files",
                "db_table": "lead_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "note_nn",
                    models.TextField(
                        help_text="Add notes about customer interactions or requirements",
                        verbose_name="Note",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, db_column="Tags", null=True, verbose_name="Tags"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        db_column="Is Done", default=False, verbose_name="Is Done"
                    ),
                ),
                (
                    "is_reminder",
                    models.BooleanField(
                        db_column="Is_Reminder",
                        default=False,
                        verbose_name="Is Reminder",
                    ),
                ),
                (
                    "follow_up_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="Follow_up_Scheduled",
                        null=True,
                        verbose_name="Follow-up Scheduled",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Note",
                "verbose_name_plural": "Lead Notes",
                "db_table": "lead_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadStatusTimeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "title_nn",
                    models.CharField(
                        db_column="Title", max_length=300, verbose_name="Title"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Status History",
                "verbose_name_plural": "Lead Status History",
                "db_table": "lead_status_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomToDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Room_To_Design",
                        max_length=50,
                        unique=True,
                        verbose_name="Room To Design",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Service_Type",
                        max_length=50,
                        verbose_name="Service Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
