# Generated by Django 5.2.1 on 2025-09-22 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brandtype",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="brandtype",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="customerlead",
            name="assigned_to_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="Assigned_To",
                help_text="Sales person responsible for this lead",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Salesman",
            ),
        ),
        migrations.AddField(
            model_name="customerlead",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="customerlead",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="leadfile",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="leadfile",
            name="lead_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="leads_app.customerlead",
                verbose_name="Customer Lead",
            ),
        ),
        migrations.AddField(
            model_name="leadfile",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="leadnote",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="leadnote",
            name="lead_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="leads_app.customerlead",
                verbose_name="Customer Lead",
            ),
        ),
        migrations.AddField(
            model_name="leadnote",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="leadstatustimeline",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="leadstatustimeline",
            name="lead_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="leads_app.customerlead",
                verbose_name="Customer Lead",
            ),
        ),
        migrations.AddField(
            model_name="leadstatustimeline",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="roomtodesign",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="roomtodesign",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="created_by",
            field=models.ForeignKey(
                db_column="Created_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="updated_by",
            field=models.ForeignKey(
                db_column="Updated_By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
    ]
