# Generated by Django 5.2.1 on 2025-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadnote",
            name="tags",
            field=models.JSONField(
                blank=True, db_column="Tags", default=list, verbose_name="Tags"
            ),
        ),
    ]
