# Generated by Django 5.2.1 on 2025-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_column="Start_Date", verbose_name="Start Date"),
                ),
                (
                    "duration_in_days",
                    models.PositiveIntegerField(
                        db_column="Duration_Days", verbose_name="Duration (Days)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(db_column="End_Date", verbose_name="End Date"),
                ),
                (
                    "total_budget",
                    models.IntegerField(
                        db_column="Total_Budget", default=0, verbose_name="Total Budget"
                    ),
                ),
                (
                    "total_amount_received",
                    models.IntegerField(
                        db_column="Total_Amount_Received",
                        default=0,
                        verbose_name="Total Received",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        db_column="Progress", default=0, verbose_name="Progress (%)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="Status",
                        default="Ongoing",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Detail",
                "verbose_name_plural": "Client Details",
                "db_table": "Client_Details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Client", "Client"), ("Project", "Project")],
                        db_column="Expence_Level",
                        max_length=50,
                        verbose_name="Expense Level",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_column="Expense_Date", verbose_name="Expense Date"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="Amount", default=0, verbose_name="Amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Expense",
                "verbose_name_plural": "Client Expenses",
                "db_table": "Client_Expense",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientExpenseSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        blank=True,
                        db_column="Expense_Date",
                        null=True,
                        verbose_name="Expense Date",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        db_column="Vendor",
                        max_length=255,
                        null=True,
                        verbose_name="Vendor",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="Notes",
                        max_length=500,
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        db_column="Quantity", default=0, verbose_name="Quantity"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="amount", default=0, verbose_name="amount"
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(
                        blank=True,
                        db_column="Expense_Category",
                        max_length=50,
                        null=True,
                        verbose_name="Expense Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        db_column="Status",
                        default="Submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_column="Submitted_At"),
                ),
                (
                    "acted_at",
                    models.DateTimeField(blank=True, db_column="Acted_At", null=True),
                ),
            ],
            options={
                "verbose_name": "Saved Client Expense Submission",
                "verbose_name_plural": "Saved Client Expense Submissions",
                "db_table": "Saved_Client_Expense_Submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientPaymanets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="Amount", default=0, verbose_name="Amount"
                    ),
                ),
                (
                    "mode_of_payment",
                    models.CharField(
                        db_column="Mode_Of_Payment",
                        max_length=20,
                        verbose_name="Mode of Payment",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        db_column="Payment_date", verbose_name="Payment Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Payment",
                "verbose_name_plural": "Client Payments",
                "db_table": "Client_Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "title_nn",
                    models.CharField(
                        db_column="Title", max_length=150, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        db_column="Description",
                        max_length=300,
                        verbose_name="Description",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, db_column="Tags", null=True, verbose_name="Tags"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        db_column="Attachment",
                        null=True,
                        upload_to="clientTimeline/",
                        verbose_name="File Attachment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Timeline",
                "verbose_name_plural": "Client Timelines",
                "db_table": "Client_Timeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectExpenseSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        blank=True,
                        db_column="Expense_Date",
                        null=True,
                        verbose_name="Expense Date",
                    ),
                ),
                (
                    "expense",
                    models.CharField(
                        blank=True,
                        db_column="Expense",
                        max_length=255,
                        null=True,
                        verbose_name="Expense",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        db_column="Notes",
                        max_length=500,
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="amount", default=0, verbose_name="amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        db_column="Status",
                        default="Submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_column="Submitted_At"),
                ),
                (
                    "acted_at",
                    models.DateTimeField(blank=True, db_column="Acted_At", null=True),
                ),
            ],
            options={
                "verbose_name": "Saved Project Expense Submission",
                "verbose_name_plural": "Saved Project Expense Submissions",
                "db_table": "Saved_Project_Expense_Submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedClientExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Submitted", "Submitted")],
                        db_column="Status",
                        default="Draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "draft_number",
                    models.UUIDField(
                        db_column="Draft_Number", verbose_name="Draft Number"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_column="Expense_Date", verbose_name="Expense Date"
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        db_column="Vendor", max_length=255, verbose_name="Vendor"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        db_column="Notes", max_length=500, verbose_name="Notes"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        db_column="Quantity", default=0, verbose_name="Quantity"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="amount", default=0, verbose_name="amount"
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(
                        db_column="Expense_Category",
                        max_length=50,
                        verbose_name="Expense Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Client Expense",
                "verbose_name_plural": "Saved Client Expenses",
                "db_table": "Saved_Client_Expense",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedProjectExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Submitted", "Submitted")],
                        db_column="Status",
                        default="Draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "draft_number",
                    models.UUIDField(
                        db_column="Draft_Number", verbose_name="Draft Number"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_column="Expense_Date", verbose_name="Expense Date"
                    ),
                ),
                (
                    "expense",
                    models.CharField(
                        db_column="Expense", max_length=255, verbose_name="Expense"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        db_column="Notes", max_length=500, verbose_name="Notes"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="amount", default=0, verbose_name="amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Project Expense",
                "verbose_name_plural": "Saved Project Expenses",
                "db_table": "Saved_Project_Expense",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "sprint_name",
                    models.CharField(
                        db_column="Sprint_Name",
                        max_length=255,
                        verbose_name="Sprint Name",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_column="Start_Date", verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(db_column="End_Date", verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Complete", "Complete"),
                            ("Pending", "Pending"),
                            ("In-progress", "In-progress"),
                        ],
                        db_column="Status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        db_column="Points", default=0, verbose_name="Points"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="Description",
                        null=True,
                        verbose_name="Sprint Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SprintChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        db_column="Description", verbose_name="Description"
                    ),
                ),
                (
                    "is_completed_ind",
                    models.BooleanField(
                        db_column="Is_Completed_Ind",
                        default=False,
                        verbose_name="Is Completed Ind",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
