# Generated by Django 5.2.1 on 2025-09-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_management", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedprojectexpense",
            name="client_details_fk",
            field=models.ForeignKey(
                db_column="Client_Detail_FK",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_project_expenses",
                to="client_management.clientdetails",
                verbose_name="Client",
            ),
            preserve_default=False,
        ),
    ]
