# Generated by Django 5.2.1 on 2025-09-26 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_management", "0003_savedprojectexpense_client_details_fk"),
        ("quotations_app", "0002_initial"),
        ("vendor_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_column="Expense_Date", verbose_name="Expense Date"
                    ),
                ),
                (
                    "expense",
                    models.CharField(
                        db_column="Expense", max_length=255, verbose_name="Expense"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        db_column="Notes", max_length=500, verbose_name="Notes"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        db_column="Amount", default=0, verbose_name="Amount"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        db_column="Approved_By",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_project_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "client_details_fk",
                    models.ForeignKey(
                        db_column="Client_Detail_FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_client_details",
                        to="client_management.clientdetails",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "manager_fk",
                    models.ForeignKey(
                        db_column="Manager_FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_client_expenses_project",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        blank=True,
                        db_column="Materials",
                        related_name="project_expenses",
                        to="vendor_app.material",
                        verbose_name="Materials",
                    ),
                ),
                (
                    "project_details_fk",
                    models.ForeignKey(
                        db_column="Project_FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_expenses",
                        to="quotations_app.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        db_column="Submitted_By",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_project_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_column="Vendors",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendor_app.vendor",
                        verbose_name="Vendors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Expense",
                "verbose_name_plural": "Project Expenses",
                "db_table": "Project_Expense",
                "ordering": ["-created_at"],
                "unique_together": {("project_details_fk", "expense_date")},
            },
        ),
    ]
