# Generated by Django 5.2.1 on 2025-09-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_management", "0004_projectexpense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectexpense",
            name="materials",
        ),
    ]
