# Generated by Django 5.2.1 on 2025-09-28 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_management", "0005_remove_projectexpense_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "activity_date",
                    models.DateTimeField(db_column="Date", verbose_name="Date"),
                ),
                (
                    "activity",
                    models.CharField(
                        db_column="Activity", max_length=255, verbose_name="Activity"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        db_column="Client_Name",
                        max_length=255,
                        null=True,
                        verbose_name="Client Name",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        db_column="Service_Type",
                        max_length=100,
                        null=True,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True, db_column="Source_Type", max_length=100, null=True
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(blank=True, db_column="Source_Id", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recent_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Activity",
                "verbose_name_plural": "Recent Activities",
                "db_table": "recent_activities",
                "ordering": ["-activity_date"],
            },
        ),
    ]
