# Generated by Django 5.2.1 on 2025-09-22 02:39

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BHKType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "bhk_name",
                    models.CharField(
                        db_column="Bhk_Name", max_length=20, verbose_name="BHK Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientCompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "company_name_nn",
                    models.CharField(
                        db_column="Company_Name",
                        max_length=200,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="Email", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address_nn",
                    models.TextField(db_column="Address", verbose_name="Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_column="Phone", max_length=15, verbose_name="Phone"
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        db_column="GST_Number",
                        max_length=20,
                        null=True,
                        verbose_name="GST Number",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        db_column="PAN_Number",
                        max_length=20,
                        null=True,
                        verbose_name="PAN Number",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        db_column="Logo_Img",
                        null=True,
                        upload_to=utils.utils.company_logo_upload_path,
                        verbose_name="Logo Img",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        db_column="Website",
                        null=True,
                        verbose_name="Website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        db_column="Item_Name", max_length=50, verbose_name="Item Name"
                    ),
                ),
                (
                    "has_dimension",
                    models.BooleanField(
                        db_column="Has_Dimension",
                        default=True,
                        verbose_name="Has Dimension",
                    ),
                ),
                (
                    "item_description",
                    models.CharField(
                        blank=True,
                        db_column="Item_Description",
                        max_length=100,
                        null=True,
                        verbose_name="Item Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True,
                        db_column="price_per_unit",
                        decimal_places=2,
                        help_text="Automatically filled from Material.base_price if not set",
                        max_digits=10,
                        null=True,
                        verbose_name="Price per Unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        db_column="Tier_Name", max_length=50, verbose_name="Tier Name"
                    ),
                ),
                (
                    "tier_description",
                    models.TextField(
                        blank=True,
                        db_column="Tier_Description",
                        null=True,
                        verbose_name="Tier Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "milestone_name",
                    models.CharField(
                        db_column="Milestone_Name",
                        max_length=100,
                        verbose_name="Milestone Name",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        db_column="Percentage",
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Percentage",
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(db_column="Amount", verbose_name="Amount"),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        db_column="Is_Paid", default=False, verbose_name="Is Paid"
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        db_column="Paid_Date",
                        null=True,
                        verbose_name="Paid Date",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        db_column="Project_Name",
                        max_length=255,
                        null=True,
                        verbose_name="Project Name",
                    ),
                ),
                (
                    "city_or_area",
                    models.CharField(
                        blank=True,
                        db_column="City_Or_Area",
                        max_length=255,
                        verbose_name="City/Area",
                    ),
                ),
                (
                    "society_type",
                    models.CharField(
                        blank=True,
                        db_column="Society_Type",
                        max_length=100,
                        verbose_name="Society Type",
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        blank=True,
                        db_column="Pin_Code",
                        max_length=6,
                        verbose_name="Pin Code",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "quotation_title",
                    models.CharField(
                        blank=True,
                        db_column="Quotation_Title",
                        max_length=100,
                        null=True,
                        verbose_name="Quotation Title",
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(
                        db_column="Quotation_Number",
                        max_length=50,
                        unique=True,
                        verbose_name="Quotation Number",
                    ),
                ),
                (
                    "scope_of_work",
                    models.JSONField(
                        blank=True,
                        db_column="Scope_Of_Work_Id",
                        default=list,
                        null=True,
                        verbose_name="Scope Of Work Id",
                    ),
                ),
                (
                    "quotation_date",
                    models.DateField(
                        db_column="Quotation_Date",
                        null=True,
                        verbose_name="Quotation Date",
                    ),
                ),
                (
                    "valid_days",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="Valid_Days",
                        default=0,
                        null=True,
                        verbose_name="Valid Days",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        db_column="Valid_Until", null=True, verbose_name="Valid Until"
                    ),
                ),
                (
                    "subtotal",
                    models.BigIntegerField(
                        db_column="Subtotal", default=0, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        db_column="Discount_Percentage",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        db_column="Discount_Amount",
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        db_column="Tax_Percentage",
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name="Tax (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.BigIntegerField(
                        db_column="Tax_Amount", default=0, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "round_off",
                    models.DecimalField(
                        db_column="Round_Off",
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Round Off",
                    ),
                ),
                (
                    "grand_total",
                    models.BigIntegerField(
                        db_column="Grand_Total", default=0, verbose_name="Grand Total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Sent", "Sent"),
                            ("Approved", "Approved"),
                        ],
                        db_column="Status",
                        default="Draft",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="Notes", null=True, verbose_name="Notes"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "item_length",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="Item_Length",
                        null=True,
                        verbose_name="Item Length",
                    ),
                ),
                (
                    "item_height",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="Item_Height",
                        null=True,
                        verbose_name="Item Height",
                    ),
                ),
                (
                    "item_quantity",
                    models.DecimalField(
                        db_column="Quantity",
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        db_column="Rate",
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount",
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuotationRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        db_column="Room_Name",
                        max_length=50,
                        null=True,
                        verbose_name="Room Name",
                    ),
                ),
                (
                    "total_room_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="Total_Room_Amount",
                        default=0,
                        verbose_name="Total Room Amount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuotationTermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        db_column="Terms_And_Conditions",
                        null=True,
                        verbose_name="Terms_And_Conditions",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        db_column="Internal_Notes",
                        null=True,
                        verbose_name="Internal Notes",
                    ),
                ),
                (
                    "footer_tagline",
                    models.CharField(
                        blank=True,
                        db_column="Footer_Tagline",
                        max_length=255,
                        verbose_name="Footer Tagline",
                    ),
                ),
                (
                    "quotation_logo",
                    models.ImageField(
                        blank=True,
                        db_column="Logo_Img",
                        null=True,
                        upload_to=utils.utils.quotation_logo_upload_path,
                        verbose_name="Logo Img",
                    ),
                ),
                (
                    "show_contact_info",
                    models.BooleanField(
                        db_column="Show_Contact_Info",
                        default=True,
                        verbose_name="Show_Contact_Info",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        db_column="Room_Name", max_length=50, verbose_name="Room Name"
                    ),
                ),
                (
                    "room_description",
                    models.CharField(
                        blank=True,
                        db_column="Room_Description",
                        max_length=250,
                        null=True,
                        verbose_name="Room Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScopeOfWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "scope_of_work",
                    models.CharField(
                        db_column="Scope_of_Work",
                        max_length=20,
                        verbose_name="Scope Of Work",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShutterFinish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "shutter_finish_name",
                    models.CharField(
                        db_column="Shutter_Finish_name",
                        max_length=100,
                        verbose_name="Shutter Finish Name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_column="Description",
                        max_length=250,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "unit_abbreviation",
                    models.CharField(
                        db_column="Unit_Abbreviation",
                        max_length=10,
                        verbose_name="Unit Abbreviation",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        blank=True,
                        db_column="Unit_Name",
                        max_length=20,
                        null=True,
                        verbose_name="Unit Name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
