# Generated by Django 5.2.1 on 2025-09-22 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Name", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name_nn",
                    models.CharField(
                        db_column="Vendor_Name",
                        max_length=150,
                        verbose_name="Vendor/Shop Name",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_column="Location",
                        max_length=150,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        db_column="Address",
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "phone_number_nn",
                    models.CharField(
                        db_column="Phone_Number",
                        max_length=15,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_column="Email",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True,
                        db_column="Extra_Info",
                        null=True,
                        verbose_name="Extra Information",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        db_column="Materials",
                        related_name="vendors",
                        to="vendor_app.material",
                        verbose_name="Materials",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "db_table": "vendor_app_vendor",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "price_nn",
                    models.DecimalField(
                        db_column="Price",
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Price",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "material_fk",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_prices",
                        to="vendor_app.material",
                        verbose_name="Material ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "vendor_fk",
                    models.ForeignKey(
                        db_column="vendor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_prices",
                        to="vendor_app.vendor",
                        verbose_name="Vendor ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Material Price",
                "verbose_name_plural": "Vendor Material Prices",
                "db_table": "vendor_app_material_price",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name_nn",
                    models.CharField(
                        db_column="Work_Type",
                        max_length=100,
                        unique=True,
                        verbose_name="Work Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Type",
                "verbose_name_plural": "Work Types",
                "db_table": "vendor_app_work_type",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "name_nn",
                    models.CharField(
                        db_column="Worker_Name",
                        max_length=150,
                        verbose_name="Worker Name",
                    ),
                ),
                (
                    "phone_number_nn",
                    models.CharField(
                        db_column="Phone_Number",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_column="Email",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "status_nn",
                    models.CharField(
                        choices=[
                            ("Assigned", "Assigned"),
                            ("Available", "Available"),
                            ("Leave", "Leave"),
                        ],
                        db_column="Status",
                        default="Available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True,
                        db_column="Extra_Info",
                        null=True,
                        verbose_name="Extra Information",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="Created_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="Updated_By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "work_type_fk",
                    models.ForeignKey(
                        blank=True,
                        db_column="Work_Type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="vendor_app.worktype",
                        verbose_name="Work Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "db_table": "vendor_app_worker",
                "ordering": ["-created_at"],
            },
        ),
    ]
